### ISSUE TITLE
gold earned with WoW mobile app

### ISSUE THREAD

**Issue by Kmitza** [Septh/WoW-Broker_Cash#3]
Is it intended that the addon dosent display gold earned when the charachter wasnt online - for example via the WoW mobile APP. 
I complete alot of gold missions with the app and the addon dosent register gold gains (day/week/month) for the character that earned gold (completed follower missions) at all...

**Comment by Septh** [comment]
Actually, this is not _really_ intended, but there is no way an addon can tell what happens when the player isn't online.

I guess I could check at login if the gold amount is the same than the last time it was recorded and take appropriate actions if it is not. But then it would be hard to tell _when_ the change (gain or loss) occurred - was it the day before? The week before?

This requires some thinking. I'm completely open to suggestions.

**Comment by Kmitza** [comment]
Does it really matter WHEN it occured? The addon should record the change at login and credit it to current day/week/month/year. I think it would be the easiest to implement. 

The way it works now is pointless IMHO, since it dosent show any gain/loss of gold at all.

**Comment by Septh** [comment]
Version 2.01 is released and does exactly that. Thanks.
